import 'package:localsend_app/gen/assets.gen.dart';

/// A mobile money service through which users can send a donation to
/// support Aika's development.
class DonationMethod {
  /// Display name of the service (e.g. "Nita").
  final String name;

  /// Logo shown on the corresponding card.
  final AssetGenImage logo;

  const DonationMethod({required this.name, required this.logo});
}

/// The mobile money number used to receive donations.
///
/// This is the ONLY place this number should be defined. Every widget that
/// displays or copies it (see `donation_page.dart`) reads it from here, so
/// updating it later only requires changing this one line.
const String kDonationPhoneNumber = '94961793';

/// The list of payment methods displayed on the "Support Aika" section of
/// the donation page, in display order.
///
/// To add, remove, rename, or re-brand a payment method, edit this list
/// only:
/// - `name` is shown as-is under the logo.
/// - `logo` must reference an `AssetGenImage` for a PNG placed in
///   `assets/img/` (see `lib/gen/assets.gen.dart`, regenerated by
///   `flutter pub run build_runner build` once a real asset is added).
final List<DonationMethod> kDonationMethods = [
  DonationMethod(name: 'Nita', logo: Assets.img.logoNita),
  DonationMethod(name: 'Amana', logo: Assets.img.logoAmana),
  DonationMethod(name: 'Wave', logo: Assets.img.logoWave),
];
