display_name: Aika
packager: Bachir Abdoul Kader
packagerEmail: bachirabdoulkader62331@gmail.com
url: https://naniger.com
buildArch: x86_64
license: Apache-2.0

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: A modern app to transfer and share files between devices
summary: Share files easily with Aika
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
