// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class ChatConversations extends Table
    with TableInfo<ChatConversations, ChatConversationsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ChatConversations(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> peerFingerprint = GeneratedColumn<String>(
    'peer_fingerprint',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> peerAlias = GeneratedColumn<String>(
    'peer_alias',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> peerDeviceModel = GeneratedColumn<String>(
    'peer_device_model',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> lastSeenAt = GeneratedColumn<int>(
    'last_seen_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> unreadCount = GeneratedColumn<int>(
    'unread_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> lastMessagePreview =
      GeneratedColumn<String>(
        'last_message_preview',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> lastMessageAt = GeneratedColumn<int>(
    'last_message_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  late final GeneratedColumn<int> peerChatProtocol = GeneratedColumn<int>(
    'peer_chat_protocol',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    peerFingerprint,
    peerAlias,
    peerDeviceModel,
    lastSeenAt,
    unreadCount,
    lastMessagePreview,
    lastMessageAt,
    createdAt,
    peerChatProtocol,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'chat_conversations';
  @override
  Set<GeneratedColumn> get $primaryKey => {peerFingerprint};
  @override
  ChatConversationsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChatConversationsData(
      peerFingerprint: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}peer_fingerprint'],
      )!,
      peerAlias: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}peer_alias'],
      )!,
      peerDeviceModel: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}peer_device_model'],
      ),
      lastSeenAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}last_seen_at'],
      ),
      unreadCount: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}unread_count'],
      )!,
      lastMessagePreview: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}last_message_preview'],
      ),
      lastMessageAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}last_message_at'],
      ),
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      peerChatProtocol: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}peer_chat_protocol'],
      ),
    );
  }

  @override
  ChatConversations createAlias(String alias) {
    return ChatConversations(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(peer_fingerprint)'];
  @override
  bool get dontWriteConstraints => true;
}

class ChatConversationsData extends DataClass
    implements Insertable<ChatConversationsData> {
  final String peerFingerprint;
  final String peerAlias;
  final String? peerDeviceModel;
  final int? lastSeenAt;
  final int unreadCount;
  final String? lastMessagePreview;
  final int? lastMessageAt;
  final int createdAt;
  final int? peerChatProtocol;
  const ChatConversationsData({
    required this.peerFingerprint,
    required this.peerAlias,
    this.peerDeviceModel,
    this.lastSeenAt,
    required this.unreadCount,
    this.lastMessagePreview,
    this.lastMessageAt,
    required this.createdAt,
    this.peerChatProtocol,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['peer_fingerprint'] = Variable<String>(peerFingerprint);
    map['peer_alias'] = Variable<String>(peerAlias);
    if (!nullToAbsent || peerDeviceModel != null) {
      map['peer_device_model'] = Variable<String>(peerDeviceModel);
    }
    if (!nullToAbsent || lastSeenAt != null) {
      map['last_seen_at'] = Variable<int>(lastSeenAt);
    }
    map['unread_count'] = Variable<int>(unreadCount);
    if (!nullToAbsent || lastMessagePreview != null) {
      map['last_message_preview'] = Variable<String>(lastMessagePreview);
    }
    if (!nullToAbsent || lastMessageAt != null) {
      map['last_message_at'] = Variable<int>(lastMessageAt);
    }
    map['created_at'] = Variable<int>(createdAt);
    if (!nullToAbsent || peerChatProtocol != null) {
      map['peer_chat_protocol'] = Variable<int>(peerChatProtocol);
    }
    return map;
  }

  ChatConversationsCompanion toCompanion(bool nullToAbsent) {
    return ChatConversationsCompanion(
      peerFingerprint: Value(peerFingerprint),
      peerAlias: Value(peerAlias),
      peerDeviceModel: peerDeviceModel == null && nullToAbsent
          ? const Value.absent()
          : Value(peerDeviceModel),
      lastSeenAt: lastSeenAt == null && nullToAbsent
          ? const Value.absent()
          : Value(lastSeenAt),
      unreadCount: Value(unreadCount),
      lastMessagePreview: lastMessagePreview == null && nullToAbsent
          ? const Value.absent()
          : Value(lastMessagePreview),
      lastMessageAt: lastMessageAt == null && nullToAbsent
          ? const Value.absent()
          : Value(lastMessageAt),
      createdAt: Value(createdAt),
      peerChatProtocol: peerChatProtocol == null && nullToAbsent
          ? const Value.absent()
          : Value(peerChatProtocol),
    );
  }

  factory ChatConversationsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return ChatConversationsData(
      peerFingerprint: serializer.fromJson<String>(json['peerFingerprint']),
      peerAlias: serializer.fromJson<String>(json['peerAlias']),
      peerDeviceModel: serializer.fromJson<String?>(json['peerDeviceModel']),
      lastSeenAt: serializer.fromJson<int?>(json['lastSeenAt']),
      unreadCount: serializer.fromJson<int>(json['unreadCount']),
      lastMessagePreview: serializer.fromJson<String?>(
        json['lastMessagePreview'],
      ),
      lastMessageAt: serializer.fromJson<int?>(json['lastMessageAt']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      peerChatProtocol: serializer.fromJson<int?>(json['peerChatProtocol']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'peerFingerprint': serializer.toJson<String>(peerFingerprint),
      'peerAlias': serializer.toJson<String>(peerAlias),
      'peerDeviceModel': serializer.toJson<String?>(peerDeviceModel),
      'lastSeenAt': serializer.toJson<int?>(lastSeenAt),
      'unreadCount': serializer.toJson<int>(unreadCount),
      'lastMessagePreview': serializer.toJson<String?>(lastMessagePreview),
      'lastMessageAt': serializer.toJson<int?>(lastMessageAt),
      'createdAt': serializer.toJson<int>(createdAt),
      'peerChatProtocol': serializer.toJson<int?>(peerChatProtocol),
    };
  }

  ChatConversationsData copyWith({
    String? peerFingerprint,
    String? peerAlias,
    Value<String?> peerDeviceModel = const Value.absent(),
    Value<int?> lastSeenAt = const Value.absent(),
    int? unreadCount,
    Value<String?> lastMessagePreview = const Value.absent(),
    Value<int?> lastMessageAt = const Value.absent(),
    int? createdAt,
    Value<int?> peerChatProtocol = const Value.absent(),
  }) => ChatConversationsData(
    peerFingerprint: peerFingerprint ?? this.peerFingerprint,
    peerAlias: peerAlias ?? this.peerAlias,
    peerDeviceModel: peerDeviceModel.present
        ? peerDeviceModel.value
        : this.peerDeviceModel,
    lastSeenAt: lastSeenAt.present ? lastSeenAt.value : this.lastSeenAt,
    unreadCount: unreadCount ?? this.unreadCount,
    lastMessagePreview: lastMessagePreview.present
        ? lastMessagePreview.value
        : this.lastMessagePreview,
    lastMessageAt: lastMessageAt.present
        ? lastMessageAt.value
        : this.lastMessageAt,
    createdAt: createdAt ?? this.createdAt,
    peerChatProtocol: peerChatProtocol.present
        ? peerChatProtocol.value
        : this.peerChatProtocol,
  );
  ChatConversationsData copyWithCompanion(ChatConversationsCompanion data) {
    return ChatConversationsData(
      peerFingerprint: data.peerFingerprint.present
          ? data.peerFingerprint.value
          : this.peerFingerprint,
      peerAlias: data.peerAlias.present ? data.peerAlias.value : this.peerAlias,
      peerDeviceModel: data.peerDeviceModel.present
          ? data.peerDeviceModel.value
          : this.peerDeviceModel,
      lastSeenAt: data.lastSeenAt.present
          ? data.lastSeenAt.value
          : this.lastSeenAt,
      unreadCount: data.unreadCount.present
          ? data.unreadCount.value
          : this.unreadCount,
      lastMessagePreview: data.lastMessagePreview.present
          ? data.lastMessagePreview.value
          : this.lastMessagePreview,
      lastMessageAt: data.lastMessageAt.present
          ? data.lastMessageAt.value
          : this.lastMessageAt,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      peerChatProtocol: data.peerChatProtocol.present
          ? data.peerChatProtocol.value
          : this.peerChatProtocol,
    );
  }

  @override
  String toString() {
    return (StringBuffer('ChatConversationsData(')
          ..write('peerFingerprint: $peerFingerprint, ')
          ..write('peerAlias: $peerAlias, ')
          ..write('peerDeviceModel: $peerDeviceModel, ')
          ..write('lastSeenAt: $lastSeenAt, ')
          ..write('unreadCount: $unreadCount, ')
          ..write('lastMessagePreview: $lastMessagePreview, ')
          ..write('lastMessageAt: $lastMessageAt, ')
          ..write('createdAt: $createdAt, ')
          ..write('peerChatProtocol: $peerChatProtocol')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    peerFingerprint,
    peerAlias,
    peerDeviceModel,
    lastSeenAt,
    unreadCount,
    lastMessagePreview,
    lastMessageAt,
    createdAt,
    peerChatProtocol,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is ChatConversationsData &&
          other.peerFingerprint == this.peerFingerprint &&
          other.peerAlias == this.peerAlias &&
          other.peerDeviceModel == this.peerDeviceModel &&
          other.lastSeenAt == this.lastSeenAt &&
          other.unreadCount == this.unreadCount &&
          other.lastMessagePreview == this.lastMessagePreview &&
          other.lastMessageAt == this.lastMessageAt &&
          other.createdAt == this.createdAt &&
          other.peerChatProtocol == this.peerChatProtocol);
}

class ChatConversationsCompanion
    extends UpdateCompanion<ChatConversationsData> {
  final Value<String> peerFingerprint;
  final Value<String> peerAlias;
  final Value<String?> peerDeviceModel;
  final Value<int?> lastSeenAt;
  final Value<int> unreadCount;
  final Value<String?> lastMessagePreview;
  final Value<int?> lastMessageAt;
  final Value<int> createdAt;
  final Value<int?> peerChatProtocol;
  final Value<int> rowid;
  const ChatConversationsCompanion({
    this.peerFingerprint = const Value.absent(),
    this.peerAlias = const Value.absent(),
    this.peerDeviceModel = const Value.absent(),
    this.lastSeenAt = const Value.absent(),
    this.unreadCount = const Value.absent(),
    this.lastMessagePreview = const Value.absent(),
    this.lastMessageAt = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.peerChatProtocol = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  ChatConversationsCompanion.insert({
    required String peerFingerprint,
    required String peerAlias,
    this.peerDeviceModel = const Value.absent(),
    this.lastSeenAt = const Value.absent(),
    this.unreadCount = const Value.absent(),
    this.lastMessagePreview = const Value.absent(),
    this.lastMessageAt = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.peerChatProtocol = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : peerFingerprint = Value(peerFingerprint),
       peerAlias = Value(peerAlias);
  static Insertable<ChatConversationsData> custom({
    Expression<String>? peerFingerprint,
    Expression<String>? peerAlias,
    Expression<String>? peerDeviceModel,
    Expression<int>? lastSeenAt,
    Expression<int>? unreadCount,
    Expression<String>? lastMessagePreview,
    Expression<int>? lastMessageAt,
    Expression<int>? createdAt,
    Expression<int>? peerChatProtocol,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (peerFingerprint != null) 'peer_fingerprint': peerFingerprint,
      if (peerAlias != null) 'peer_alias': peerAlias,
      if (peerDeviceModel != null) 'peer_device_model': peerDeviceModel,
      if (lastSeenAt != null) 'last_seen_at': lastSeenAt,
      if (unreadCount != null) 'unread_count': unreadCount,
      if (lastMessagePreview != null)
        'last_message_preview': lastMessagePreview,
      if (lastMessageAt != null) 'last_message_at': lastMessageAt,
      if (createdAt != null) 'created_at': createdAt,
      if (peerChatProtocol != null) 'peer_chat_protocol': peerChatProtocol,
      if (rowid != null) 'rowid': rowid,
    });
  }

  ChatConversationsCompanion copyWith({
    Value<String>? peerFingerprint,
    Value<String>? peerAlias,
    Value<String?>? peerDeviceModel,
    Value<int?>? lastSeenAt,
    Value<int>? unreadCount,
    Value<String?>? lastMessagePreview,
    Value<int?>? lastMessageAt,
    Value<int>? createdAt,
    Value<int?>? peerChatProtocol,
    Value<int>? rowid,
  }) {
    return ChatConversationsCompanion(
      peerFingerprint: peerFingerprint ?? this.peerFingerprint,
      peerAlias: peerAlias ?? this.peerAlias,
      peerDeviceModel: peerDeviceModel ?? this.peerDeviceModel,
      lastSeenAt: lastSeenAt ?? this.lastSeenAt,
      unreadCount: unreadCount ?? this.unreadCount,
      lastMessagePreview: lastMessagePreview ?? this.lastMessagePreview,
      lastMessageAt: lastMessageAt ?? this.lastMessageAt,
      createdAt: createdAt ?? this.createdAt,
      peerChatProtocol: peerChatProtocol ?? this.peerChatProtocol,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (peerFingerprint.present) {
      map['peer_fingerprint'] = Variable<String>(peerFingerprint.value);
    }
    if (peerAlias.present) {
      map['peer_alias'] = Variable<String>(peerAlias.value);
    }
    if (peerDeviceModel.present) {
      map['peer_device_model'] = Variable<String>(peerDeviceModel.value);
    }
    if (lastSeenAt.present) {
      map['last_seen_at'] = Variable<int>(lastSeenAt.value);
    }
    if (unreadCount.present) {
      map['unread_count'] = Variable<int>(unreadCount.value);
    }
    if (lastMessagePreview.present) {
      map['last_message_preview'] = Variable<String>(lastMessagePreview.value);
    }
    if (lastMessageAt.present) {
      map['last_message_at'] = Variable<int>(lastMessageAt.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (peerChatProtocol.present) {
      map['peer_chat_protocol'] = Variable<int>(peerChatProtocol.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('ChatConversationsCompanion(')
          ..write('peerFingerprint: $peerFingerprint, ')
          ..write('peerAlias: $peerAlias, ')
          ..write('peerDeviceModel: $peerDeviceModel, ')
          ..write('lastSeenAt: $lastSeenAt, ')
          ..write('unreadCount: $unreadCount, ')
          ..write('lastMessagePreview: $lastMessagePreview, ')
          ..write('lastMessageAt: $lastMessageAt, ')
          ..write('createdAt: $createdAt, ')
          ..write('peerChatProtocol: $peerChatProtocol, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class ChatMessages extends Table
    with TableInfo<ChatMessages, ChatMessagesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ChatMessages(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES chat_conversations(peer_fingerprint)',
  );
  late final GeneratedColumn<String> direction = GeneratedColumn<String>(
    'direction',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> contentType = GeneratedColumn<String>(
    'content_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> body = GeneratedColumn<String>(
    'body',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> attachmentPath = GeneratedColumn<String>(
    'attachment_path',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> attachmentFileName =
      GeneratedColumn<String>(
        'attachment_file_name',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> attachmentSize = GeneratedColumn<int>(
    'attachment_size',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> errorMessage = GeneratedColumn<String>(
    'error_message',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sentAt = GeneratedColumn<int>(
    'sent_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> deliveredAt = GeneratedColumn<int>(
    'delivered_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> readAt = GeneratedColumn<int>(
    'read_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    conversationId,
    direction,
    contentType,
    body,
    attachmentPath,
    attachmentFileName,
    attachmentSize,
    status,
    errorMessage,
    createdAt,
    sentAt,
    deliveredAt,
    readAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'chat_messages';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  ChatMessagesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChatMessagesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      conversationId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}conversation_id'],
      )!,
      direction: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}direction'],
      )!,
      contentType: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}content_type'],
      )!,
      body: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}body'],
      ),
      attachmentPath: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}attachment_path'],
      ),
      attachmentFileName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}attachment_file_name'],
      ),
      attachmentSize: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}attachment_size'],
      ),
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}status'],
      )!,
      errorMessage: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}error_message'],
      ),
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      sentAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sent_at'],
      ),
      deliveredAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}delivered_at'],
      ),
      readAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}read_at'],
      ),
    );
  }

  @override
  ChatMessages createAlias(String alias) {
    return ChatMessages(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class ChatMessagesData extends DataClass
    implements Insertable<ChatMessagesData> {
  final String id;
  final String conversationId;
  final String direction;
  final String contentType;
  final String? body;
  final String? attachmentPath;
  final String? attachmentFileName;
  final int? attachmentSize;
  final String status;
  final String? errorMessage;
  final int createdAt;
  final int? sentAt;
  final int? deliveredAt;
  final int? readAt;
  const ChatMessagesData({
    required this.id,
    required this.conversationId,
    required this.direction,
    required this.contentType,
    this.body,
    this.attachmentPath,
    this.attachmentFileName,
    this.attachmentSize,
    required this.status,
    this.errorMessage,
    required this.createdAt,
    this.sentAt,
    this.deliveredAt,
    this.readAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['conversation_id'] = Variable<String>(conversationId);
    map['direction'] = Variable<String>(direction);
    map['content_type'] = Variable<String>(contentType);
    if (!nullToAbsent || body != null) {
      map['body'] = Variable<String>(body);
    }
    if (!nullToAbsent || attachmentPath != null) {
      map['attachment_path'] = Variable<String>(attachmentPath);
    }
    if (!nullToAbsent || attachmentFileName != null) {
      map['attachment_file_name'] = Variable<String>(attachmentFileName);
    }
    if (!nullToAbsent || attachmentSize != null) {
      map['attachment_size'] = Variable<int>(attachmentSize);
    }
    map['status'] = Variable<String>(status);
    if (!nullToAbsent || errorMessage != null) {
      map['error_message'] = Variable<String>(errorMessage);
    }
    map['created_at'] = Variable<int>(createdAt);
    if (!nullToAbsent || sentAt != null) {
      map['sent_at'] = Variable<int>(sentAt);
    }
    if (!nullToAbsent || deliveredAt != null) {
      map['delivered_at'] = Variable<int>(deliveredAt);
    }
    if (!nullToAbsent || readAt != null) {
      map['read_at'] = Variable<int>(readAt);
    }
    return map;
  }

  ChatMessagesCompanion toCompanion(bool nullToAbsent) {
    return ChatMessagesCompanion(
      id: Value(id),
      conversationId: Value(conversationId),
      direction: Value(direction),
      contentType: Value(contentType),
      body: body == null && nullToAbsent ? const Value.absent() : Value(body),
      attachmentPath: attachmentPath == null && nullToAbsent
          ? const Value.absent()
          : Value(attachmentPath),
      attachmentFileName: attachmentFileName == null && nullToAbsent
          ? const Value.absent()
          : Value(attachmentFileName),
      attachmentSize: attachmentSize == null && nullToAbsent
          ? const Value.absent()
          : Value(attachmentSize),
      status: Value(status),
      errorMessage: errorMessage == null && nullToAbsent
          ? const Value.absent()
          : Value(errorMessage),
      createdAt: Value(createdAt),
      sentAt: sentAt == null && nullToAbsent
          ? const Value.absent()
          : Value(sentAt),
      deliveredAt: deliveredAt == null && nullToAbsent
          ? const Value.absent()
          : Value(deliveredAt),
      readAt: readAt == null && nullToAbsent
          ? const Value.absent()
          : Value(readAt),
    );
  }

  factory ChatMessagesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return ChatMessagesData(
      id: serializer.fromJson<String>(json['id']),
      conversationId: serializer.fromJson<String>(json['conversationId']),
      direction: serializer.fromJson<String>(json['direction']),
      contentType: serializer.fromJson<String>(json['contentType']),
      body: serializer.fromJson<String?>(json['body']),
      attachmentPath: serializer.fromJson<String?>(json['attachmentPath']),
      attachmentFileName: serializer.fromJson<String?>(
        json['attachmentFileName'],
      ),
      attachmentSize: serializer.fromJson<int?>(json['attachmentSize']),
      status: serializer.fromJson<String>(json['status']),
      errorMessage: serializer.fromJson<String?>(json['errorMessage']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      sentAt: serializer.fromJson<int?>(json['sentAt']),
      deliveredAt: serializer.fromJson<int?>(json['deliveredAt']),
      readAt: serializer.fromJson<int?>(json['readAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'conversationId': serializer.toJson<String>(conversationId),
      'direction': serializer.toJson<String>(direction),
      'contentType': serializer.toJson<String>(contentType),
      'body': serializer.toJson<String?>(body),
      'attachmentPath': serializer.toJson<String?>(attachmentPath),
      'attachmentFileName': serializer.toJson<String?>(attachmentFileName),
      'attachmentSize': serializer.toJson<int?>(attachmentSize),
      'status': serializer.toJson<String>(status),
      'errorMessage': serializer.toJson<String?>(errorMessage),
      'createdAt': serializer.toJson<int>(createdAt),
      'sentAt': serializer.toJson<int?>(sentAt),
      'deliveredAt': serializer.toJson<int?>(deliveredAt),
      'readAt': serializer.toJson<int?>(readAt),
    };
  }

  ChatMessagesData copyWith({
    String? id,
    String? conversationId,
    String? direction,
    String? contentType,
    Value<String?> body = const Value.absent(),
    Value<String?> attachmentPath = const Value.absent(),
    Value<String?> attachmentFileName = const Value.absent(),
    Value<int?> attachmentSize = const Value.absent(),
    String? status,
    Value<String?> errorMessage = const Value.absent(),
    int? createdAt,
    Value<int?> sentAt = const Value.absent(),
    Value<int?> deliveredAt = const Value.absent(),
    Value<int?> readAt = const Value.absent(),
  }) => ChatMessagesData(
    id: id ?? this.id,
    conversationId: conversationId ?? this.conversationId,
    direction: direction ?? this.direction,
    contentType: contentType ?? this.contentType,
    body: body.present ? body.value : this.body,
    attachmentPath: attachmentPath.present
        ? attachmentPath.value
        : this.attachmentPath,
    attachmentFileName: attachmentFileName.present
        ? attachmentFileName.value
        : this.attachmentFileName,
    attachmentSize: attachmentSize.present
        ? attachmentSize.value
        : this.attachmentSize,
    status: status ?? this.status,
    errorMessage: errorMessage.present ? errorMessage.value : this.errorMessage,
    createdAt: createdAt ?? this.createdAt,
    sentAt: sentAt.present ? sentAt.value : this.sentAt,
    deliveredAt: deliveredAt.present ? deliveredAt.value : this.deliveredAt,
    readAt: readAt.present ? readAt.value : this.readAt,
  );
  ChatMessagesData copyWithCompanion(ChatMessagesCompanion data) {
    return ChatMessagesData(
      id: data.id.present ? data.id.value : this.id,
      conversationId: data.conversationId.present
          ? data.conversationId.value
          : this.conversationId,
      direction: data.direction.present ? data.direction.value : this.direction,
      contentType: data.contentType.present
          ? data.contentType.value
          : this.contentType,
      body: data.body.present ? data.body.value : this.body,
      attachmentPath: data.attachmentPath.present
          ? data.attachmentPath.value
          : this.attachmentPath,
      attachmentFileName: data.attachmentFileName.present
          ? data.attachmentFileName.value
          : this.attachmentFileName,
      attachmentSize: data.attachmentSize.present
          ? data.attachmentSize.value
          : this.attachmentSize,
      status: data.status.present ? data.status.value : this.status,
      errorMessage: data.errorMessage.present
          ? data.errorMessage.value
          : this.errorMessage,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      sentAt: data.sentAt.present ? data.sentAt.value : this.sentAt,
      deliveredAt: data.deliveredAt.present
          ? data.deliveredAt.value
          : this.deliveredAt,
      readAt: data.readAt.present ? data.readAt.value : this.readAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('ChatMessagesData(')
          ..write('id: $id, ')
          ..write('conversationId: $conversationId, ')
          ..write('direction: $direction, ')
          ..write('contentType: $contentType, ')
          ..write('body: $body, ')
          ..write('attachmentPath: $attachmentPath, ')
          ..write('attachmentFileName: $attachmentFileName, ')
          ..write('attachmentSize: $attachmentSize, ')
          ..write('status: $status, ')
          ..write('errorMessage: $errorMessage, ')
          ..write('createdAt: $createdAt, ')
          ..write('sentAt: $sentAt, ')
          ..write('deliveredAt: $deliveredAt, ')
          ..write('readAt: $readAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    conversationId,
    direction,
    contentType,
    body,
    attachmentPath,
    attachmentFileName,
    attachmentSize,
    status,
    errorMessage,
    createdAt,
    sentAt,
    deliveredAt,
    readAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is ChatMessagesData &&
          other.id == this.id &&
          other.conversationId == this.conversationId &&
          other.direction == this.direction &&
          other.contentType == this.contentType &&
          other.body == this.body &&
          other.attachmentPath == this.attachmentPath &&
          other.attachmentFileName == this.attachmentFileName &&
          other.attachmentSize == this.attachmentSize &&
          other.status == this.status &&
          other.errorMessage == this.errorMessage &&
          other.createdAt == this.createdAt &&
          other.sentAt == this.sentAt &&
          other.deliveredAt == this.deliveredAt &&
          other.readAt == this.readAt);
}

class ChatMessagesCompanion extends UpdateCompanion<ChatMessagesData> {
  final Value<String> id;
  final Value<String> conversationId;
  final Value<String> direction;
  final Value<String> contentType;
  final Value<String?> body;
  final Value<String?> attachmentPath;
  final Value<String?> attachmentFileName;
  final Value<int?> attachmentSize;
  final Value<String> status;
  final Value<String?> errorMessage;
  final Value<int> createdAt;
  final Value<int?> sentAt;
  final Value<int?> deliveredAt;
  final Value<int?> readAt;
  final Value<int> rowid;
  const ChatMessagesCompanion({
    this.id = const Value.absent(),
    this.conversationId = const Value.absent(),
    this.direction = const Value.absent(),
    this.contentType = const Value.absent(),
    this.body = const Value.absent(),
    this.attachmentPath = const Value.absent(),
    this.attachmentFileName = const Value.absent(),
    this.attachmentSize = const Value.absent(),
    this.status = const Value.absent(),
    this.errorMessage = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.sentAt = const Value.absent(),
    this.deliveredAt = const Value.absent(),
    this.readAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  ChatMessagesCompanion.insert({
    required String id,
    required String conversationId,
    required String direction,
    required String contentType,
    this.body = const Value.absent(),
    this.attachmentPath = const Value.absent(),
    this.attachmentFileName = const Value.absent(),
    this.attachmentSize = const Value.absent(),
    required String status,
    this.errorMessage = const Value.absent(),
    required int createdAt,
    this.sentAt = const Value.absent(),
    this.deliveredAt = const Value.absent(),
    this.readAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       conversationId = Value(conversationId),
       direction = Value(direction),
       contentType = Value(contentType),
       status = Value(status),
       createdAt = Value(createdAt);
  static Insertable<ChatMessagesData> custom({
    Expression<String>? id,
    Expression<String>? conversationId,
    Expression<String>? direction,
    Expression<String>? contentType,
    Expression<String>? body,
    Expression<String>? attachmentPath,
    Expression<String>? attachmentFileName,
    Expression<int>? attachmentSize,
    Expression<String>? status,
    Expression<String>? errorMessage,
    Expression<int>? createdAt,
    Expression<int>? sentAt,
    Expression<int>? deliveredAt,
    Expression<int>? readAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (conversationId != null) 'conversation_id': conversationId,
      if (direction != null) 'direction': direction,
      if (contentType != null) 'content_type': contentType,
      if (body != null) 'body': body,
      if (attachmentPath != null) 'attachment_path': attachmentPath,
      if (attachmentFileName != null)
        'attachment_file_name': attachmentFileName,
      if (attachmentSize != null) 'attachment_size': attachmentSize,
      if (status != null) 'status': status,
      if (errorMessage != null) 'error_message': errorMessage,
      if (createdAt != null) 'created_at': createdAt,
      if (sentAt != null) 'sent_at': sentAt,
      if (deliveredAt != null) 'delivered_at': deliveredAt,
      if (readAt != null) 'read_at': readAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  ChatMessagesCompanion copyWith({
    Value<String>? id,
    Value<String>? conversationId,
    Value<String>? direction,
    Value<String>? contentType,
    Value<String?>? body,
    Value<String?>? attachmentPath,
    Value<String?>? attachmentFileName,
    Value<int?>? attachmentSize,
    Value<String>? status,
    Value<String?>? errorMessage,
    Value<int>? createdAt,
    Value<int?>? sentAt,
    Value<int?>? deliveredAt,
    Value<int?>? readAt,
    Value<int>? rowid,
  }) {
    return ChatMessagesCompanion(
      id: id ?? this.id,
      conversationId: conversationId ?? this.conversationId,
      direction: direction ?? this.direction,
      contentType: contentType ?? this.contentType,
      body: body ?? this.body,
      attachmentPath: attachmentPath ?? this.attachmentPath,
      attachmentFileName: attachmentFileName ?? this.attachmentFileName,
      attachmentSize: attachmentSize ?? this.attachmentSize,
      status: status ?? this.status,
      errorMessage: errorMessage ?? this.errorMessage,
      createdAt: createdAt ?? this.createdAt,
      sentAt: sentAt ?? this.sentAt,
      deliveredAt: deliveredAt ?? this.deliveredAt,
      readAt: readAt ?? this.readAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (conversationId.present) {
      map['conversation_id'] = Variable<String>(conversationId.value);
    }
    if (direction.present) {
      map['direction'] = Variable<String>(direction.value);
    }
    if (contentType.present) {
      map['content_type'] = Variable<String>(contentType.value);
    }
    if (body.present) {
      map['body'] = Variable<String>(body.value);
    }
    if (attachmentPath.present) {
      map['attachment_path'] = Variable<String>(attachmentPath.value);
    }
    if (attachmentFileName.present) {
      map['attachment_file_name'] = Variable<String>(attachmentFileName.value);
    }
    if (attachmentSize.present) {
      map['attachment_size'] = Variable<int>(attachmentSize.value);
    }
    if (status.present) {
      map['status'] = Variable<String>(status.value);
    }
    if (errorMessage.present) {
      map['error_message'] = Variable<String>(errorMessage.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (sentAt.present) {
      map['sent_at'] = Variable<int>(sentAt.value);
    }
    if (deliveredAt.present) {
      map['delivered_at'] = Variable<int>(deliveredAt.value);
    }
    if (readAt.present) {
      map['read_at'] = Variable<int>(readAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('ChatMessagesCompanion(')
          ..write('id: $id, ')
          ..write('conversationId: $conversationId, ')
          ..write('direction: $direction, ')
          ..write('contentType: $contentType, ')
          ..write('body: $body, ')
          ..write('attachmentPath: $attachmentPath, ')
          ..write('attachmentFileName: $attachmentFileName, ')
          ..write('attachmentSize: $attachmentSize, ')
          ..write('status: $status, ')
          ..write('errorMessage: $errorMessage, ')
          ..write('createdAt: $createdAt, ')
          ..write('sentAt: $sentAt, ')
          ..write('deliveredAt: $deliveredAt, ')
          ..write('readAt: $readAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class ChatOutboxEntries extends Table
    with TableInfo<ChatOutboxEntries, ChatOutboxEntriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ChatOutboxEntries(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> messageId = GeneratedColumn<String>(
    'message_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES chat_messages(id)',
  );
  late final GeneratedColumn<int> attempts = GeneratedColumn<int>(
    'attempts',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> nextAttemptAt = GeneratedColumn<int>(
    'next_attempt_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  @override
  List<GeneratedColumn> get $columns => [
    messageId,
    attempts,
    nextAttemptAt,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'chat_outbox_entries';
  @override
  Set<GeneratedColumn> get $primaryKey => {messageId};
  @override
  ChatOutboxEntriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChatOutboxEntriesData(
      messageId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}message_id'],
      )!,
      attempts: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}attempts'],
      )!,
      nextAttemptAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}next_attempt_at'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  ChatOutboxEntries createAlias(String alias) {
    return ChatOutboxEntries(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(message_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class ChatOutboxEntriesData extends DataClass
    implements Insertable<ChatOutboxEntriesData> {
  final String messageId;
  final int attempts;
  final int nextAttemptAt;
  final int createdAt;
  const ChatOutboxEntriesData({
    required this.messageId,
    required this.attempts,
    required this.nextAttemptAt,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['message_id'] = Variable<String>(messageId);
    map['attempts'] = Variable<int>(attempts);
    map['next_attempt_at'] = Variable<int>(nextAttemptAt);
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  ChatOutboxEntriesCompanion toCompanion(bool nullToAbsent) {
    return ChatOutboxEntriesCompanion(
      messageId: Value(messageId),
      attempts: Value(attempts),
      nextAttemptAt: Value(nextAttemptAt),
      createdAt: Value(createdAt),
    );
  }

  factory ChatOutboxEntriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return ChatOutboxEntriesData(
      messageId: serializer.fromJson<String>(json['messageId']),
      attempts: serializer.fromJson<int>(json['attempts']),
      nextAttemptAt: serializer.fromJson<int>(json['nextAttemptAt']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'messageId': serializer.toJson<String>(messageId),
      'attempts': serializer.toJson<int>(attempts),
      'nextAttemptAt': serializer.toJson<int>(nextAttemptAt),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  ChatOutboxEntriesData copyWith({
    String? messageId,
    int? attempts,
    int? nextAttemptAt,
    int? createdAt,
  }) => ChatOutboxEntriesData(
    messageId: messageId ?? this.messageId,
    attempts: attempts ?? this.attempts,
    nextAttemptAt: nextAttemptAt ?? this.nextAttemptAt,
    createdAt: createdAt ?? this.createdAt,
  );
  ChatOutboxEntriesData copyWithCompanion(ChatOutboxEntriesCompanion data) {
    return ChatOutboxEntriesData(
      messageId: data.messageId.present ? data.messageId.value : this.messageId,
      attempts: data.attempts.present ? data.attempts.value : this.attempts,
      nextAttemptAt: data.nextAttemptAt.present
          ? data.nextAttemptAt.value
          : this.nextAttemptAt,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('ChatOutboxEntriesData(')
          ..write('messageId: $messageId, ')
          ..write('attempts: $attempts, ')
          ..write('nextAttemptAt: $nextAttemptAt, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(messageId, attempts, nextAttemptAt, createdAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is ChatOutboxEntriesData &&
          other.messageId == this.messageId &&
          other.attempts == this.attempts &&
          other.nextAttemptAt == this.nextAttemptAt &&
          other.createdAt == this.createdAt);
}

class ChatOutboxEntriesCompanion
    extends UpdateCompanion<ChatOutboxEntriesData> {
  final Value<String> messageId;
  final Value<int> attempts;
  final Value<int> nextAttemptAt;
  final Value<int> createdAt;
  final Value<int> rowid;
  const ChatOutboxEntriesCompanion({
    this.messageId = const Value.absent(),
    this.attempts = const Value.absent(),
    this.nextAttemptAt = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  ChatOutboxEntriesCompanion.insert({
    required String messageId,
    this.attempts = const Value.absent(),
    required int nextAttemptAt,
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : messageId = Value(messageId),
       nextAttemptAt = Value(nextAttemptAt);
  static Insertable<ChatOutboxEntriesData> custom({
    Expression<String>? messageId,
    Expression<int>? attempts,
    Expression<int>? nextAttemptAt,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (messageId != null) 'message_id': messageId,
      if (attempts != null) 'attempts': attempts,
      if (nextAttemptAt != null) 'next_attempt_at': nextAttemptAt,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  ChatOutboxEntriesCompanion copyWith({
    Value<String>? messageId,
    Value<int>? attempts,
    Value<int>? nextAttemptAt,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return ChatOutboxEntriesCompanion(
      messageId: messageId ?? this.messageId,
      attempts: attempts ?? this.attempts,
      nextAttemptAt: nextAttemptAt ?? this.nextAttemptAt,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (messageId.present) {
      map['message_id'] = Variable<String>(messageId.value);
    }
    if (attempts.present) {
      map['attempts'] = Variable<int>(attempts.value);
    }
    if (nextAttemptAt.present) {
      map['next_attempt_at'] = Variable<int>(nextAttemptAt.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('ChatOutboxEntriesCompanion(')
          ..write('messageId: $messageId, ')
          ..write('attempts: $attempts, ')
          ..write('nextAttemptAt: $nextAttemptAt, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class ChatBlockedDevices extends Table
    with TableInfo<ChatBlockedDevices, ChatBlockedDevicesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ChatBlockedDevices(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> fingerprint = GeneratedColumn<String>(
    'fingerprint',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> alias = GeneratedColumn<String>(
    'alias',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> blockedAt = GeneratedColumn<int>(
    'blocked_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  @override
  List<GeneratedColumn> get $columns => [fingerprint, alias, blockedAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'chat_blocked_devices';
  @override
  Set<GeneratedColumn> get $primaryKey => {fingerprint};
  @override
  ChatBlockedDevicesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChatBlockedDevicesData(
      fingerprint: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}fingerprint'],
      )!,
      alias: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}alias'],
      )!,
      blockedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}blocked_at'],
      )!,
    );
  }

  @override
  ChatBlockedDevices createAlias(String alias) {
    return ChatBlockedDevices(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(fingerprint)'];
  @override
  bool get dontWriteConstraints => true;
}

class ChatBlockedDevicesData extends DataClass
    implements Insertable<ChatBlockedDevicesData> {
  final String fingerprint;
  final String alias;
  final int blockedAt;
  const ChatBlockedDevicesData({
    required this.fingerprint,
    required this.alias,
    required this.blockedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['fingerprint'] = Variable<String>(fingerprint);
    map['alias'] = Variable<String>(alias);
    map['blocked_at'] = Variable<int>(blockedAt);
    return map;
  }

  ChatBlockedDevicesCompanion toCompanion(bool nullToAbsent) {
    return ChatBlockedDevicesCompanion(
      fingerprint: Value(fingerprint),
      alias: Value(alias),
      blockedAt: Value(blockedAt),
    );
  }

  factory ChatBlockedDevicesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return ChatBlockedDevicesData(
      fingerprint: serializer.fromJson<String>(json['fingerprint']),
      alias: serializer.fromJson<String>(json['alias']),
      blockedAt: serializer.fromJson<int>(json['blockedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'fingerprint': serializer.toJson<String>(fingerprint),
      'alias': serializer.toJson<String>(alias),
      'blockedAt': serializer.toJson<int>(blockedAt),
    };
  }

  ChatBlockedDevicesData copyWith({
    String? fingerprint,
    String? alias,
    int? blockedAt,
  }) => ChatBlockedDevicesData(
    fingerprint: fingerprint ?? this.fingerprint,
    alias: alias ?? this.alias,
    blockedAt: blockedAt ?? this.blockedAt,
  );
  ChatBlockedDevicesData copyWithCompanion(ChatBlockedDevicesCompanion data) {
    return ChatBlockedDevicesData(
      fingerprint: data.fingerprint.present
          ? data.fingerprint.value
          : this.fingerprint,
      alias: data.alias.present ? data.alias.value : this.alias,
      blockedAt: data.blockedAt.present ? data.blockedAt.value : this.blockedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('ChatBlockedDevicesData(')
          ..write('fingerprint: $fingerprint, ')
          ..write('alias: $alias, ')
          ..write('blockedAt: $blockedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(fingerprint, alias, blockedAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is ChatBlockedDevicesData &&
          other.fingerprint == this.fingerprint &&
          other.alias == this.alias &&
          other.blockedAt == this.blockedAt);
}

class ChatBlockedDevicesCompanion
    extends UpdateCompanion<ChatBlockedDevicesData> {
  final Value<String> fingerprint;
  final Value<String> alias;
  final Value<int> blockedAt;
  final Value<int> rowid;
  const ChatBlockedDevicesCompanion({
    this.fingerprint = const Value.absent(),
    this.alias = const Value.absent(),
    this.blockedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  ChatBlockedDevicesCompanion.insert({
    required String fingerprint,
    required String alias,
    this.blockedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : fingerprint = Value(fingerprint),
       alias = Value(alias);
  static Insertable<ChatBlockedDevicesData> custom({
    Expression<String>? fingerprint,
    Expression<String>? alias,
    Expression<int>? blockedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (fingerprint != null) 'fingerprint': fingerprint,
      if (alias != null) 'alias': alias,
      if (blockedAt != null) 'blocked_at': blockedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  ChatBlockedDevicesCompanion copyWith({
    Value<String>? fingerprint,
    Value<String>? alias,
    Value<int>? blockedAt,
    Value<int>? rowid,
  }) {
    return ChatBlockedDevicesCompanion(
      fingerprint: fingerprint ?? this.fingerprint,
      alias: alias ?? this.alias,
      blockedAt: blockedAt ?? this.blockedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (fingerprint.present) {
      map['fingerprint'] = Variable<String>(fingerprint.value);
    }
    if (alias.present) {
      map['alias'] = Variable<String>(alias.value);
    }
    if (blockedAt.present) {
      map['blocked_at'] = Variable<int>(blockedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('ChatBlockedDevicesCompanion(')
          ..write('fingerprint: $fingerprint, ')
          ..write('alias: $alias, ')
          ..write('blockedAt: $blockedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV2 extends GeneratedDatabase {
  DatabaseAtV2(QueryExecutor e) : super(e);
  late final ChatConversations chatConversations = ChatConversations(this);
  late final ChatMessages chatMessages = ChatMessages(this);
  late final ChatOutboxEntries chatOutboxEntries = ChatOutboxEntries(this);
  late final ChatBlockedDevices chatBlockedDevices = ChatBlockedDevices(this);
  late final Index chatMessagesConversationCreated = Index(
    'chat_messages_conversation_created',
    'CREATE INDEX chat_messages_conversation_created ON chat_messages (conversation_id, created_at)',
  );
  late final Index chatOutboxNextAttempt = Index(
    'chat_outbox_next_attempt',
    'CREATE INDEX chat_outbox_next_attempt ON chat_outbox_entries (next_attempt_at)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    chatConversations,
    chatMessages,
    chatOutboxEntries,
    chatBlockedDevices,
    chatMessagesConversationCreated,
    chatOutboxNextAttempt,
  ];
  @override
  int get schemaVersion => 2;
}
