// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'chat.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Creates the chat hub with this device's certificate and private key (PEM),
/// the same as the HTTP server's TLS identity.
RsChatHub createChatHub({required String cert, required String privateKey}) =>
    RustLib.instance.api.crateApiChatCreateChatHub(cert: cert, privateKey: privateKey);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsChatHub>>
abstract class RsChatHub implements RustOpaqueInterface {
  /// Closes a connection; a `Disconnected` event follows.
  Future<void> close({required String connectionId});

  /// Opens a chat connection, accepted only if the peer's certificate has
  /// [fingerprint]. Returns the connection ID.
  Future<String> connect({required String ip, required int port, required String fingerprint});

  /// Emits the chat events. Can only be listened to once.
  Stream<RsChatEvent> listen();

  /// Queues a text frame on a connection.
  Future<void> send({required String connectionId, required String text});

  /// Closes every connection and refuses new ones.
  Future<void> shutdown();
}

@freezed
sealed class RsChatError with _$RsChatError implements FrbException {
  const RsChatError._();

  /// The peer presented a certificate with another fingerprint:
  /// possibly another device impersonating it.
  const factory RsChatError.fingerprintMismatch() = RsChatError_FingerprintMismatch;

  /// The peer has no chat WebSocket (e.g. v1.0.3, HTTP 404) or refused it.
  const factory RsChatError.unsupported({
    required int status,
  }) = RsChatError_Unsupported;
  const factory RsChatError.tooManyConnections() = RsChatError_TooManyConnections;
  const factory RsChatError.notConnected() = RsChatError_NotConnected;
  const factory RsChatError.messageTooLarge() = RsChatError_MessageTooLarge;
  const factory RsChatError.timeout() = RsChatError_Timeout;
  const factory RsChatError.other({
    required String message,
  }) = RsChatError_Other;
}

@freezed
sealed class RsChatEvent with _$RsChatEvent {
  const RsChatEvent._();

  const factory RsChatEvent.connected({
    required String connectionId,

    /// Verified SHA-256 fingerprint (uppercase hex) of the peer certificate.
    required String fingerprint,
    required String ip,

    /// `true` when this device initiated the connection.
    required bool outbound,
  }) = RsChatEvent_Connected;
  const factory RsChatEvent.message({
    required String connectionId,
    required String text,
  }) = RsChatEvent_Message;
  const factory RsChatEvent.disconnected({
    required String connectionId,
    required String reason,
  }) = RsChatEvent_Disconnected;
}
